version: '3.8'

services:
  db:
    container_name: training.proyectothera.com.ar_db
    image: linuxserver/mariadb:latest
    env_file: docker/production/.env
    volumes:
      - db_data:/config
    logging:
      driver: none
    restart: unless-stopped

  web:
    container_name: training.proyectothera.com.ar_web
    image: project-thera/thera-training-webapp
    build:
      context: .
      dockerfile: docker/production/web/Dockerfile
      args:
        # downgraded because of this
        # https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
        - RUBY_VERSION=2.6.6-alpine3.12
        - BUNDLER_VERSION=2.2.14
    env_file: docker/production/.env
    restart: unless-stopped
    volumes:
      - web_gems:/usr/local/bundle
      - web_modules:/usr/local/app/node_modules
      - web_uploads:/usr/local/app/private/uploads
    depends_on:
      - db

volumes:
  db_data:
  web_gems:
  web_modules:
  web_uploads: