version: '3.8'

services:
  db:
    container_name: thera-training-webapp_db
    image: mariadb:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    logging:
      driver: none

  web:
    container_name: thera-training-webapp_web
    image: project-thera/thera-training-webapp
    build:
      context: .
      dockerfile: docker/production/Dockerfile
      args:
        RUBY_VERSION: '2.7.2'
        BUNDLER_VERSION: '2.2.14'
    env_file: docker/production/.env
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db_data: