# https://docs.docker.com/compose/rails/

version: '3.8'

services:
  db:
    container_name: thera-training-webapp_db
    image: mariadb:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    logging:
      driver: none

  web: &web
    container_name: thera-training-webapp_web
    build:
      context: .
      dockerfile: ./docker/development/web/Dockerfile
      args:
        RUBY_VERSION: '2.7.2'
        BUNDLER_VERSION: '2.2.14'
    environment:
      - SECREY_KEY_BASE=9e803c5c2d3f977ca3bd09220f008ca2e076d28bfe4b09427e212bab0c14942ba26ee6
      - RAILS_MASTER_KEY=55104b2c20be7e20f0894f5972e04316
      - EDITOR=vi
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    volumes:
      - .:/usr/local/app:cached
      # - .:/app
      - gems:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db

  webpacker:
    container_name: thera-training-webapp_webpacker
    build:
      context: .
      dockerfile: ./docker/development/webpacker/Dockerfile
    ports:
      - 3035:3035
    depends_on:
      - web

  phpmyadmin:
    container_name: thera-training-webapp_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 80:80
    environment:
      - PMA_USER=root
    logging:
      driver: none

volumes:
  db_data:
  gems:
